import React from 'react';
import { useGlobalContext } from '../context/AppContext';

export const TemplateExporter = () => {
  const { config } = useGlobalContext();

  const generateCSSFile = () => {
    const complexCSS = `
/* Generated by CSS Background Creator
  Theme: ${config.themeName}
  Mode: ${config.complexity}
*/

:root {
  --bg-primary: ${config.secondaryColor};
  --box-color: ${config.primaryColor};
  --anim-speed: ${config.speed}s;
}

.bg-container {
  position: fixed;
  top: 0; left: 0;
  width: 100vw; height: 100vh;
  background-color: var(--bg-primary);
  z-index: -1;
  overflow: hidden;
  background-image: 
    linear-gradient(rgba(255,255,255,0.03) 1px, transparent 1px),
    linear-gradient(90deg, rgba(255,255,255,0.03) 1px, transparent 1px);
  background-size: 50px 50px;
}

.animated-box {
  width: 50px; height: 50px;
  background-color: var(--box-color);
  opacity: 0;
  animation: ${config.complexity === 'pulse' ? 'pulseAnim' : 'scatterAnim'} var(--anim-speed) infinite ease-in-out;
}

@keyframes pulseAnim {
  0%, 100% { opacity: 0.05; }
  50% { opacity: 0.4; }
}

@keyframes scatterAnim {
  0%, 100% { opacity: 0.1; transform: translate(0, 0); }
  50% { opacity: 0.5; transform: translate(20px, -20px) scale(1.1); }
}
    `.trim();

    const element = document.createElement("a");
    const file = new Blob([complexCSS], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = `${config.themeName.replace(/\s+/g, '_')}_styles.css`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div style={{ marginTop: '20px' }}>
      <button 
        onClick={generateCSSFile}
        style={{ 
          width: '100%', 
          padding: '12px', 
          borderRadius: '8px', 
          background: 'transparent', 
          color: '#4c4e72', 
          border: '2px solid #4c4e72',
          fontWeight: 'bold', 
          cursor: 'pointer'
        }}
      >
        Download Complex CSS File
      </button>
    </div>
  );
};

export default TemplateExporter;